inherit_from:
  - https://raw.githubusercontent.com/rubocop-hq/rubocop/master/config/enabled.yml

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
